version: "3.9"
name: "odoo-erp-17"
services:
  odoo:
    image: builong99/odoo-adm:17
    build: ../.docker
    ports:
      - "8090:8069"
      - "8072:8072"
    volumes:
      - ../:/opt/odoo
      - odoo_data:/home/odoo/.local/share/Odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM} && tail -f /dev/null"
    environment:
      PYTHON_PATH: "/opt/odoo/.runner/run.sh"
      START_ODOO: ""
      ODOO_PARAM: ""
    depends_on:
      - postgres
    restart: unless-stopped
    tty: true
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    ports:
      - "5432:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true

volumes:
  odoo_data:
  postgres17_data:
