name: "odoo18"
services:
  odoo:
    image: builong99/odoo:18
    build: ../.docker
    volumes:
      - ../:/opt/odoo
      - odoo_filestore_data:/var/log/odoo
    command: bash -c "$${PYTHON_PATH} $${START_ODOO} $${ODOO_PARAM}"
    entrypoint: []
    environment:
      PYTHON_PATH: "/opt/odoo/.runner/run.sh"
      START_ODOO: ""
      ODOO_PARAM: ""
    network_mode: host
    restart: unless-stopped
    tty: true

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: odoo
    network_mode: host
    restart: unless-stopped
    tty: true

volumes:
  odoo_filestore_data:
  postgres_data: